"""CSN-V4 semantic constants — categorical shade IDs, no ordinal naming."""
from __future__ import annotations

from typing import Final

MODEL_NAME: Final[str] = "CarpetShadeNetV4"
SHORT_NAME: Final[str] = "CSN-V4"

CLASS_WHITE: Final[int] = 0
CLASS_SHADE_200: Final[int] = 1
CLASS_SHADE_150: Final[int] = 2
CLASS_SHADE_100: Final[int] = 3
NUM_CLASSES: Final[int] = 4
NUM_SHADE_SUBTYPES: Final[int] = 3

# Backward-compatible aliases (deprecated)
CLASS_LIGHT = CLASS_SHADE_200
CLASS_MEDIUM = CLASS_SHADE_150
CLASS_DARK = CLASS_SHADE_100
NUM_LEVEL_CLASSES = NUM_SHADE_SUBTYPES

IGNORE_INDEX: Final[int] = -100

GRAY_BLACK: Final[int] = 0
GRAY_WHITE: Final[int] = 255
GRAY_SHADE_200: Final[int] = 200
GRAY_SHADE_150: Final[int] = 150
GRAY_SHADE_100: Final[int] = 100

GRAY_LIGHT = GRAY_SHADE_200
GRAY_MEDIUM = GRAY_SHADE_150
GRAY_DARK = GRAY_SHADE_100

ALLOWED_OUTPUT_GRAY: Final[frozenset[int]] = frozenset(
    {GRAY_BLACK, GRAY_WHITE, GRAY_SHADE_200, GRAY_SHADE_150, GRAY_SHADE_100}
)

CLASS_TO_GRAY: Final[dict[int, int]] = {
    CLASS_WHITE: GRAY_WHITE,
    CLASS_SHADE_200: GRAY_SHADE_200,
    CLASS_SHADE_150: GRAY_SHADE_150,
    CLASS_SHADE_100: GRAY_SHADE_100,
}

SEMANTIC_GRAY_TO_CLASS: Final[dict[int, int]] = {
    GRAY_WHITE: CLASS_WHITE,
    GRAY_SHADE_200: CLASS_SHADE_200,
    GRAY_SHADE_150: CLASS_SHADE_150,
    GRAY_SHADE_100: CLASS_SHADE_100,
}

SHADE_SUBTYPE_LIGHT: Final[int] = 0
SHADE_SUBTYPE_MEDIUM: Final[int] = 1
SHADE_SUBTYPE_DARK: Final[int] = 2
SHADE_SUBTYPE_IGNORE: Final[int] = 255

SHADE_LEVEL_LIGHT = SHADE_SUBTYPE_LIGHT
SHADE_LEVEL_MEDIUM = SHADE_SUBTYPE_MEDIUM
SHADE_LEVEL_DARK = SHADE_SUBTYPE_DARK
SHADE_LEVEL_IGNORE = SHADE_SUBTYPE_IGNORE

SHADE_SUBTYPE_TO_CLASS: Final[dict[int, int]] = {
    SHADE_SUBTYPE_LIGHT: CLASS_SHADE_200,
    SHADE_SUBTYPE_MEDIUM: CLASS_SHADE_150,
    SHADE_SUBTYPE_DARK: CLASS_SHADE_100,
}

AFFINITY_OFFSETS: Final[tuple[int, ...]] = (1, 2, 4, 8)
AFFINITY_NUM_CHANNELS: Final[int] = len(AFFINITY_OFFSETS) * 2
